export const editorTuning = {
  ganeshaDxConstraints: {
    polygonVertexCounts: [3, 4],
    paletteId: { min: 0, max: 15 },
    texturePage: { min: 0, max: 3 },
    textureAtlas: { pageWidth: 256, pageHeight: 256, atlasHeight: 1024 },
    terrainX: { min: 0, max: 255 },
    terrainZ: { min: 0, max: 127 },
    terrainLevel: { min: 0, max: 1 },
    byte: { min: 0, max: 255 },
    nibble: { min: 0, max: 15 },
    twoBit: { min: 0, max: 3 },
    vertexPosition: {
      x: { min: -32768, max: 32767 },
      y: { min: -32768, max: 32767 },
      z: { min: -32768, max: 32767 },
    },
    normalElevation: { min: -90, max: 90 },
    normalAzimuth: { min: 0, max: 360 },
  },
  camera: {
    basePixelsPerWorldUnit: 88,
    buttonZoomStep: 0.01,
    cameraDistance: 1000,
    defaultZoom: 0.025,
    farZoomPreset: 0.015,
    gameZoomPreset: 0.025,
    keyboardPanStep: 10,
    maxElevationDegrees: 80,
    maxZoom: 0.5,
    minCameraClearance: 0.35,
    minElevationDegrees: 5,
    minZoom: 0.005,
    nearZoomPreset: 0.06,
    orbitButtonElevationStep: 5,
    orbitButtonYawStep: 15,
    orbitElevationSensitivity: 0.16,
    orbitYawSensitivity: 0.28,
    panBoundsMarginScale: 0.75,
    panBoundsMinimumMargin: 6,
    presetSnapToleranceDegrees: 0.5,
    viewportPanStep: 24,
    wheelZoomStep: 0.005,
  },
  editing: {
    gridSnapStep: 4,
    transformGizmoSize: 1.1,
    vertexNudgeStep: 1,
  },
  labels: {
    maxVisibleLabels: 120,
    polygonLabelHeight: 96,
    polygonLabelScaleX: 0.62,
    polygonLabelScaleY: 0.23,
    polygonLabelWidth: 256,
    polygonLabelYOffset: 0.12,
  },
  picking: {
    cornerSelectionRadiusPx: 7,
    vertexHandleRadius: 0.055,
    vertexHandleYOffset: 0.07,
  },
} as const;
