flowchart TD
  root["GaneshaDx"]
  root --> Common["Common"]
  root --> Environment["Environment"]
  root --> Rendering["Rendering"]
  root --> Resources["Resources"]
  Resources --> Resources_ContentDataTypes["ContentDataTypes"]
  Resources_ContentDataTypes --> Resources_ContentDataTypes_MeshAnimations["MeshAnimations"]
  Resources_ContentDataTypes --> Resources_ContentDataTypes_Palettes["Palettes"]
  Resources_ContentDataTypes --> Resources_ContentDataTypes_Polygons["Polygons"]
  Resources_ContentDataTypes --> Resources_ContentDataTypes_Terrains["Terrains"]
  Resources_ContentDataTypes --> Resources_ContentDataTypes_TextureAnimations["TextureAnimations"]
  Resources --> Resources_GnsData["GnsData"]
  Resources --> Resources_ResourceContent["ResourceContent"]
  root --> UserInterface["UserInterface"]
  UserInterface --> UserInterface_GuiDefinitions["GuiDefinitions"]
  UserInterface --> UserInterface_GuiForms["GuiForms"]
  UserInterface --> UserInterface_Input["Input"]
  UserInterface --> UserInterface_Widgets["Widgets"]