export const originalMapTitles: Record<string, string> = {
  MAP000: "Unknown",
  MAP001: "At Main Gate of Igros Castle",
  MAP002: "Back Gate of Lesalia Castle",
  MAP003: "Hall of St. Murond Temple",
  MAP004: "Office of Lesalia Castle",
  MAP005: "Roof of Riovanes Castle",
  MAP006: "At the Gate of Riovanes Castle",
  MAP007: "Inside of Riovanes Castle",
  MAP008: "Riovanes Castle",
  MAP009: "Citadel of Igros Castle",
  MAP010: "Inside of Igros Castle",
  MAP011: "Office of Igros Castle",
  MAP012: "At the Gate of Lionel Castle",
  MAP013: "Inside of Lionel Castle",
  MAP014: "Office of Lionel Castle",
  MAP015: "At the Gate of Limberry Castle (1)",
  MAP016: "Inside of Limberry Castle",
  MAP017: "Underground Cemetery of Limberry Castle",
  MAP018: "Office of Limberry Castle",
  MAP019: "At the Gate of Limberry Castle (2)",
  MAP020: "Inside of Zeltennia Castle",
  MAP021: "Zeltennia Castle",
  MAP022: "Magic City Gariland",
  MAP023: "Belouve Residence",
  MAP024: "Military Academy's Auditorium",
  MAP025: "Yardow Fort City",
  MAP026: "Weapon Storage of Yardow",
  MAP027: "Goland Coal City",
  MAP028: "Colliery Underground First Floor",
  MAP029: "Colliery Underground Second Floor",
  MAP030: "Colliery Underground Third Floor",
  MAP031: "Dorter Trade City",
  MAP032: "Slums in Dorter",
  MAP033: "Hospital in Slums",
  MAP034: "Cellar of Sand Mouse",
  MAP035: "Zaland Fort City",
  MAP036: "Church Outside of Town",
  MAP037: "Ruins Outside Zaland",
  MAP038: "Goug Machine City",
  MAP039: "Underground Passage in Goland",
  MAP040: "Slums in Goug",
  MAP041: "Besrodio's House",
  MAP042: "Warjilis Trade City",
  MAP043: "Port of Warjilis",
  MAP044: "Bervenia Free City",
  MAP045: "Ruins of Zeltennia Castle's Church",
  MAP046: "Cemetery of Heavenly Knight, Balbanes",
  MAP047: "Zarghidas Trade City",
  MAP048: "Slums of Zarghidas",
  MAP049: "Fort Zeakden",
  MAP050: "St. Murond Temple",
  MAP051: "St. Murond Temple",
  MAP052: "Chapel of St. Murond Temple",
  MAP053: "Entrance to Death City",
  MAP054: "Lost Sacred Precincts",
  MAP055: "Graveyard of Airships",
  MAP056: "Orbonne Monastery",
  MAP057: "Underground Book Storage First Floor",
  MAP058: "Underground Book Storage Second Floor",
  MAP059: "Underground Book Storage Third Floor",
  MAP060: "Underground Book Storage Fourth Floor",
  MAP061: "Underground Book Storage Fifth Floor",
  MAP062: "Chapel of Orbonne Monastery",
  MAP063: "Golgorand Execution Site",
  MAP064: "In Front of Bethla Garrison's Sluice",
  MAP065: "Granary of Bethla Garrison",
  MAP066: "South Wall of Bethla Garrison",
  MAP067: "North Wall of Bethla Garrison",
  MAP068: "Bethla Garrison",
  MAP069: "Murond Death City",
  MAP070: "Nelveska Temple",
  MAP071: "Dolbodar Swamp",
  MAP072: "Fovoham Plains",
  MAP073: "Inside of Windmill Shed",
  MAP074: "Sweegy Woods",
  MAP075: "Bervenia Volcano",
  MAP076: "Zeklaus Desert",
  MAP077: "Lenalia Plateau",
  MAP078: "Zigolis Swamp",
  MAP079: "Yuguo Woods",
  MAP080: "Araguay Woods",
  MAP081: "Grog Hill",
  MAP082: "Bed Desert",
  MAP083: "Zirekile Falls",
  MAP084: "Bariaus Hill",
  MAP085: "Mandalia Plains",
  MAP086: "Doguola Pass",
  MAP087: "Bariaus Valley",
  MAP088: "Finath River",
  MAP089: "Poeskas Lake",
  MAP090: "Germinas Peak",
  MAP091: "Thieves Fort",
  MAP092: "Igros-Belouve Residence",
  MAP093: "Broke Down Shed-Wooden Building",
  MAP094: "Broke Down Shed-Stone Building",
  MAP095: "Church",
  MAP096: "Pub",
  MAP097: "Inside Castle Gate in Lesalia",
  MAP098: "Outside Castle Gate in Lesalia",
  MAP099: "Main Street of Lesalia",
  MAP100: "Public Cemetery",
  MAP101: "Tutorial (1)",
  MAP102: "Tutorial (2)",
  MAP103: "Windmill Shed",
  MAP104: "Belouve Residence",
  MAP105: "TERMINATE",
  MAP106: "DELTA",
  MAP107: "NOGIAS",
  MAP108: "VOYAGE",
  MAP109: "BRIDGE",
  MAP110: "VALKYRIES",
  MAP111: "MLAPAN",
  MAP112: "TIGER",
  MAP113: "HORROR",
  MAP114: "END",
  MAP115: "Banished Fort",
  MAP116: "Arena",
  MAP117: "Unknown",
  MAP118: "Unknown",
  MAP119: "Unknown",
  MAP125: "Unknown",
} as const;

export function resolveOriginalMapTitle(mapId: string | null | undefined): string | undefined {
  if (!mapId) {
    return undefined;
  }

  return originalMapTitles[mapId.toUpperCase()];
}

export function formatOriginalMapLabel(
  mapId: string | null | undefined,
  label?: string | null,
): string {
  const trimmedLabel = label?.trim();
  const originalTitle = resolveOriginalMapTitle(mapId);
  if (trimmedLabel && trimmedLabel !== mapId && trimmedLabel !== originalTitle) {
    return trimmedLabel;
  }

  return originalTitle ?? trimmedLabel ?? mapId ?? "Unknown map";
}
